baseURL: https://intro-to-rmarkdown.netlify.app
languageCode: en-gb
defaultContentLanguage: en-gb
title: Intro to R Markdown
theme: hugo-tranquilpeak-theme
disqusShortname: hugo-tranquilpeak-theme
paginate: 7
canonifyurls: yes
googleAnalytics: "G-W1MKDTDR60"
permalinks:
  posts: "/:year/:month/:day/:slug/"
taxonomies:
  archive: archives
  category: categories
  tag: tags
markup:
  tableOfContents:
    endLevel: 3
    ordered: no
    startLevel: 1
author:
  bio: The resources associated with the Introduction to R Markdown by [Dr. Mateus Harrington](https://gmbernardoharrington.netlify.app/), initally offered as part of the [Researcher Summer school at Keele University 2022](https://www.keele.ac.uk/kiite/conferences/researchersummerschool/)
  # this overrides any images
  #gravatarEmail: 
  job: Bioinformatician
  location: Wales
  name: Introduction to R Markdown
  picture: ./img/rmarkdown_logo.jpg
menu:
  links:
    - identifier: github
      name: GitHub
      pre: <i class="sidebar-button-icon fab fa-lg fa-github" aria-hidden="true"></i>
      url: https://github.com/H-Mateus/intro-to-rmarkdown
      weight: 1
    - identifier: linkedin
      name: LinkedIn
      pre: <i class="sidebar-button-icon fab fa-lg fa-linkedin" aria-hidden="true"></i>
      url:  https://linkedin.com/in/gmb-harrington
      weight: 2
  main:
    - identifier: home
      name: Home
      pre: <i class="sidebar-button-icon fas fa-lg fa-home" aria-hidden="true"></i>
      url: /
      weight: 1
    # - identifier: categories
    #   name: Categories
    #   pre: <i class="sidebar-button-icon fas fa-lg fa-bookmark" aria-hidden="true"></i>
    #   url: /categories
    #   weight: 2
    # - identifier: tags
    #   name: Tags
    #   pre: <i class="sidebar-button-icon fas fa-lg fa-tags" aria-hidden="true"></i>
    #   url: /tags
    #   weight: 3
    # - identifier: archives
    #   name: Archives
    #   pre: <i class="sidebar-button-icon fas fa-lg fa-archive" aria-hidden="true"></i>
    #   url: /archives
    #   weight: 4
    - identifier: about
      name: About
      pre: <i class="sidebar-button-icon fas fa-lg fa-question" aria-hidden="true"></i>
      url: /#about
      weight: 5
  # misc:
  #   - identifier: rss
  #     name: RSS
  #     pre: <i class="sidebar-button-icon fas fa-lg fa-rss" aria-hidden="true"></i>
  #     url: /index.xml
  #     weight: 1
params:
  autoThumbnailImage: yes
  keywords:
    - workshop
    - R Markdown
    - Keele
    - teaching
  # Customize copyright value "© 2017 <CUSTOMIZATION>. All Rights Reserved"
  footer:
    copyright: '<a href="https://github.com/H-Mateus">Mateus Harrington</a>. All Rights Reserved'
  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clearReading: no
  comment:
    disqus:
      enable: yes
      shortname: hugo-tranquilpeak-theme
    gitalk:
      enable: no
      options:
        distractionFreeMode: no
        enableHotKey: yes
        language: en
        pagerDirection: first
        perPage: 10
  
  # Your blog cover picture. I STRONGLY recommend you to use a CDN to speed up loading of pages.
  # There is many free CDN like Cloudinary or you can also use indirectly
  # by using services like Google Photos.
  # Current image is on AWS S3 and delivered by AWS CloudFront.
  # Otherwise put your image in folder `static/_images/` (development)  or in `source/assets/images/` if you can't or don't want to build the theme,
  # and use relative url : `your-image.png`
  coverImage: ./img/cover.jpg
  # Enable LaTeX math rendering? yes/no
  #   If no, you can enable math on a per page basis as needed.
  math: yes
  # Enable diagram rendering? true/false
  #   If false, you can enable diagrams on a per page basis as needed.
  #diagram: yes
  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  #privacy_pack: false
  customJS:
    - async: yes
      crossorigin: anonymous
      defer: yes
      integrity: sha512-gE8KAQyFIzV1C9+GZ8TKJHZS2s+n7EjNtC+IMRn1l5+WYJTHOODUM6JSjZhFhqXmc7bG8Av6XXpckA4tYhflnw==
      src: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/apache.min.js
    - async: yes
      crossorigin: anonymous
      defer: yes
      integrity: sha512-EWROca+bote+7Oaaar1F6y74iZj1r1F9rm/ly7o+/FwJopbBaWtsFDmaKoZDd3QiGU2pGacBirHJNivmGLYrow==
      src: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/go.min.js
    - async: yes
      crossorigin: anonymous
      defer: yes
      integrity: sha512-GDVzAn0wpx1yVtQsRWmFc6PhJiLBPdUic+h4GWgljBh904O3JU10fk9EKNpVyIoPqkFn54rgL2QBG4BmUTMpiQ==
      src: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/http.min.js
    - async: yes
      crossorigin: anonymous
      defer: yes
      integrity: sha512-UgZlma8NzkrDb/NWgmLIcTrH7i/CSnLLDRFqCSNF5NGPpjKmzyM25qcoXGOup8+cDakKyaiTDd7N4dyH4YT+IA==
      src: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/less.min.js
    - async: yes
      crossorigin: anonymous
      defer: yes
      integrity: sha512-lot9koe73sfXIrUvIPM/UEhuMciN56RPyBdOyZgfO53P2lkWyyXN7J+njcxIIBRV+nVDQeiWtiXg+bLAJZDTfg==
      src: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/nginx.min.js
    - async: yes
      crossorigin: anonymous
      defer: yes
      integrity: sha512-Zd3e7XxHP00TD0Imr0PIfeM0fl0v95kMWuhyAS3Wn1UTSXTkz0OhtRgBAr4JlmADRgiXr4x7lpeUdqaGN8xIog==
      src: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/puppet.min.js
    - async: yes
      crossorigin: anonymous
      defer: yes
      integrity: sha512-qtqDO052iXMSP+5d/aE/jMtL9vIIGvONgTJziC2K/ZIB1yEGa55WVxGE9/08rSQ62EoDifS9SWVGZ7ihSLhzMA==
      src: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/scss.min.js
    - async: yes
      crossorigin: anonymous
      defer: yes
      integrity: sha512-1NmkjnEDnwwwcu28KoQF8vs3oaPFokQHbmbtwGhFfeDsQZtVFI8zW2aE9O8yMYdpdyKV/5blE4pSWw4Z/Sv97w==
      src: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/stylus.min.js
    - async: yes
      crossorigin: anonymous
      defer: yes
      integrity: sha512-B2wSfruPjr8EJL6IIzQr1eAuDwrsfIfccNf/LCEdxELCgC/S/ZMt/Uvk80aD79m7IqOqW+Sw8nbkvha20yZpzg==
      src: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/swift.min.js
    - async: yes
      crossorigin: anonymous
      defer: yes
      integrity: sha512-28oDiQZGKUVN6wQ7PSLPNipOcmkCALXKwOi7bnkyFf8QiMZQxG9EQoy/iiNx6Zxj2cG2SbVa4dXKigQhu7GiFw==
      src: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/yaml.min.js
  description: Introduction to R Markdown workshop
  header:
    rightLink:
      class: ''
      icon: ''
      url: /#about
  # Define categories will create hierarchy between parents: `categories = ["foo", "bar"]` will consider "bar" a sub-category of "foo".
  # If false it will flat categories.
  hierarchicalCategories: yes
  # Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
  imageGallery: yes
  sharingOptions:
    - icon: fab fa-facebook-square
      name: Facebook
      url: https://www.facebook.com/sharer/sharer.php?u=%s
    - icon: fab fa-twitter
      name: Twitter
      url: https://twitter.com/intent/tweet?text=%s
    - icon: fab fa-linkedin
      name: Linkedin
      url: https://www.linkedin.com/sharing/share-offsite/?url=%s
      
  # Customization
  # Define the behavior of the sidebar
  # 1: Display extra large sidebar on extra large screen, large sidebar on large screen,
  #    medium sidebar on medium screen and header bar on small screen and
  # extra large sidebar is swiped on extra large screen and large sidebar on all lower screen (default)
  # 2: Display large sidebar on large screen, medium sidebar on medium screen and
  #    header bar on small screen and large sidebar is swiped
  # 3: Display medium sidebar on large and medium screen and header bar on small screen and
  #    medium sidebar is swiped
  # 4: Display header bar on all screens, extra large sidebar is swiped on extra large screen and
  #    large sidebar is swiped on all lower screens
  # 5: Display header bar on all screens and large sidebar is swiped on large screen
  # 6: Display header bar on all screens and medium sidebar is swiped
  sidebarBehavior: 2
  syntaxHighlighter: highlight.js
  thumbnailImage: yes
  thumbnailImagePosition: left
